

CREATE TABLE [tbProjProjects](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[ProjectName] [varchar](128) NULL,
	[StartDate] [date] NULL,
	[FinishDate] [date] NULL,
	[StatusID] [int] NULL,
	[Closed] [bit] NULL,
 CONSTRAINT [PK_Projects] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO