destroy:
  runs-on: ubuntu-latest
  needs: terraform
  if: github.event.inputs.action == 'destroy'

  steps:
  - name: Checkout repository
    uses: actions/checkout@v2

  - name: Set up Terraform
    uses: hashicorp/setup-terraform@v2
    with:
      terraform_version: 1.0.8

  - name: Authenticate to Azure
    uses: azure/login@v1
    with:
      creds: ${{ secrets.AZURE_CREDENTIALS }}

  - name: Initialize Terraform
    run: terraform init

  - name: Destroy Terraform
    run: terraform destroy -auto-approve